defaults:
  batch_size: 5000
  on_conflict: upsert

sources:
  - name: fashion_sales_csv
    type: csv
    path: data/Fashion_Retail_Sales.csv
    target_table: stg_fashion_sales
    pk: [customer reference id]   #maybe change this later if needed
    schema:
      customer reference id: int
      item purchased: str
      purchase amount (usd): float
      date purchase: datetime
      review rating: float
      payment method: str
    rules:
      - rule: "purchase amount (usd) >= 0"
      - rule: "review rating BETWEEN 0 AND 5"      # but it will allow NULL
      - rule: "payment method IN ('Cash','Credit Card')"